version: '3.3'

services:
  arm-build-debug:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/app
    environment:
      WORK_DIR: '/home/app'
      BUILD_TYPE: 'Debug'
      BUILD_OUTPUT_PATH: 'cmake-build-debug-arm'

  arm-build-release:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/app
    environment:
      WORK_DIR: '/home/app'
      BUILD_TYPE: 'Release'
      BUILD_OUTPUT_PATH: 'cmake-build-release-arm'
